server:
  port: 8080
  
spring:
  config:
    import: "optional:configserver:"

eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8761/eureka