server:
  port: 8888
  
spring:
  cloud:    config:      server:        git:
          uri: https://github.com/JeanBeltrame/microservice-repo          search-paths: loja, fornecedor, transportadora#        git:#          uri: https://github.com/JeanBeltrame/desafio-loja-lecom